### ISSUE TITLE
WebSockets timing out

### ISSUE THREAD

**Issue by JanHolger** [JavaWebStack/http-router-undertow#1]
Currently the websocket implementation will timeout after 30 seconds because of the max connection time of undertow. We need to find a way to disable the max connection for websocket connections.

**Comment by x7airworker** [comment]
@JanHolger Should we move this issue to https://github.com/JavaWebStack/http-router-undertow ?

**Comment by x7airworker** [comment]
Should be fixed by commit https://github.com/JavaWebStack/http-router-undertow/commit/3ffeda5e4a4e50fe6f0e1d9aecfdd506753ab2db.
